-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\echo4\dataplane.vhd
-- Created: 2021-03-07 17:24:45
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1.01725e-08
-- Target subsystem base rate: 1.01725e-08
-- Explicit user oversample request: 2048x
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        2.08333e-05
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- output_signal                 ce_out        2.08333e-05
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dataplane
-- Source Path: echo4/dataplane
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY dataplane IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        input_signal                      :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
        delay_samples                     :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        echo_gain                         :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En15
        enable                            :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        output_signal                     :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En23
        );
END dataplane;


ARCHITECTURE rtl OF dataplane IS

  ATTRIBUTE multstyle : string;

  -- Component Declarations
  COMPONENT dataplane_tc
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          enb                             :   OUT   std_logic;
          enb_1_2048_0                    :   OUT   std_logic;
          enb_1_2048_1                    :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT echo
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          input_signal                    :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
          delay_samples                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          echo_gain                       :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En15
          output_signal                   :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En23
          );
  END COMPONENT;

  -- Component Configuration Statements
--   FOR ALL : dataplane_tc
--     USE ENTITY work.dataplane_tc(rtl);

--   FOR ALL : echo
--     USE ENTITY work.echo(rtl);

  -- Signals
  SIGNAL enb_1_2048_1                     : std_logic;
  SIGNAL enb                              : std_logic;
  SIGNAL enb_1_2048_0                     : std_logic;
  SIGNAL enable_1                         : std_logic;
  SIGNAL input_signal_1                   : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL echo_out1                        : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL echo_out1_signed                 : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL Switch_out1                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL t_bypass_reg                     : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL Switch_out1_1                    : signed(23 DOWNTO 0);  -- sfix24_En23

BEGIN
  u_dataplane_tc : dataplane_tc
    PORT MAP( clk => clk,
              reset => reset,
              clk_enable => clk_enable,
              enb => enb,
              enb_1_2048_0 => enb_1_2048_0,
              enb_1_2048_1 => enb_1_2048_1
              );

  u_echo : echo
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              enb_1_2048_0 => enb_1_2048_0,
              input_signal => input_signal,  -- sfix24_En23
              delay_samples => delay_samples,  -- uint16
              echo_gain => echo_gain,  -- ufix16_En15
              output_signal => echo_out1  -- sfix24_En23
              );

  enable_1 <= enable;

  input_signal_1 <= signed(input_signal);

  echo_out1_signed <= signed(echo_out1);

  
  Switch_out1 <= input_signal_1 WHEN enable_1 = '0' ELSE
      echo_out1_signed;

  t_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      t_bypass_reg <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2048_1 = '1' THEN
        t_bypass_reg <= Switch_out1;
      END IF;
    END IF;
  END PROCESS t_bypass_process;

  
  Switch_out1_1 <= Switch_out1 WHEN enb_1_2048_1 = '1' ELSE
      t_bypass_reg;

  output_signal <= std_logic_vector(Switch_out1_1);

  ce_out <= enb_1_2048_1;

END rtl;

